# Pre-build: writes include/wifi_secrets.h from WIFI_SSID, WIFI_PASSWORD,
# optional WIFI_GMT_OFFSET_SEC (default 0), and include/colorink_app_secrets.h
# from COLORINK_DEVICE_ID (required for every env). Keeps secrets out of git.
# WIFI_GMT_OFFSET_SEC is reserved for future use (e.g. NTP); time sync is not enabled in firmware.
#
# Values come from (highest priority first): existing process env, then
# PROJECT_ROOT/.env parsed with python-dotenv (standard dotenv syntax).
# Dependencies are installed by scripts/install_python_deps.py (see platformio.ini).

Import("env")

import json
import os
from pathlib import Path

from dotenv import load_dotenv


def merge_dotenv(project_dir: str) -> None:
    path = Path(project_dir) / ".env"
    if load_dotenv(path, override=False, encoding="utf-8"):
        print(f"Loaded environment from {path}")


def c_macro_string(s: str) -> str:
    """Escape for use inside C double-quoted string literals (SSID/password)."""
    return json.dumps(s, ensure_ascii=False)[1:-1]


def generate_wifi_secrets(project_dir: str) -> None:
    """WIFI_SSID, WIFI_PASSWORD, WIFI_GMT_OFFSET_SEC → include/wifi_secrets.h."""
    ssid = os.environ.get("WIFI_SSID", "").strip()
    password = os.environ.get("WIFI_PASSWORD", "")
    offset_raw = os.environ.get("WIFI_GMT_OFFSET_SEC", "0").strip() or "0"

    if not ssid or not password:
        print(
            "ERROR: Set WIFI_SSID and WIFI_PASSWORD before building.\n"
            "  • Copy example.env to .env (gitignored), or\n"
            "  • export WIFI_SSID=... WIFI_PASSWORD=... in the shell, then pio run"
        )
        env.Exit(1)

    try:
        offset_sec = int(offset_raw)
    except ValueError:
        print(f"ERROR: WIFI_GMT_OFFSET_SEC must be an integer, got {offset_raw!r}")
        env.Exit(1)

    out_path = Path(project_dir) / "include" / "wifi_secrets.h"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "#pragma once",
        "// Generated by scripts/gen_wifi_secrets.py — do not commit",
        "",
        f'#define WIFI_SSID "{c_macro_string(ssid)}"',
        f'#define WIFI_PASSWORD "{c_macro_string(password)}"',
        f"#define WIFI_GMT_OFFSET_SEC {offset_sec}",
        "",
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {out_path}")


def generate_colorink_app_secrets(project_dir: str) -> None:
    """COLORINK_DEVICE_ID → X-Device-ID header; required for all builds."""
    device_id = os.environ.get("COLORINK_DEVICE_ID", "").strip()

    if not device_id:
        print(
            "ERROR: Set COLORINK_DEVICE_ID before building.\n"
            "  • Add COLORINK_DEVICE_ID to .env (see example.env), or\n"
            "  • export COLORINK_DEVICE_ID=... in the shell, then pio run"
        )
        env.Exit(1)

    out_path = Path(project_dir) / "include" / "colorink_app_secrets.h"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    define_line = f'#define COLORINK_DEVICE_ID "{c_macro_string(device_id)}"'

    lines = [
        "#pragma once",
        "// Generated by scripts/gen_wifi_secrets.py — do not commit",
        "",
        define_line,
        "",
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated {out_path}")


def main() -> None:
    merge_dotenv(env["PROJECT_DIR"])

    generate_wifi_secrets(env["PROJECT_DIR"])
    generate_colorink_app_secrets(env["PROJECT_DIR"])


main()
